In [1]:
import pandas as pd
import numpy as np

### country

In [30]:
country = countryNameAndCode[['Country']]
n = len(country)
country.ix[:, 'pred_rank'] = 0
country.ix[:, 'pred_gold'] = 0
country.ix[:, 'pred_silver'] = 0
country.ix[:, 'pred_bronze'] = 0
# pred_rank
# pred_gold
# pred_silver
# pred_bronze
country.to_csv('resources/data clean/country.csv')

### economics

In [48]:
def getData(gdp, cpi, income, population):
    countryCode = gdp.index
    yearCol = gdp.columns[1:]
    tempDict = {'code': [], 'year': [], 'gdp': [], 'population': [], 'income': [], 'cpi': []}
    for c in countryCode:
        for y in yearCol:
            tempDict['code'].append(c)
            tempDict['year'].append(y)
            tempDict['gdp'].append(gdp.ix[c, y])
            tempDict['cpi'].append(cpi.ix[c, y])
            tempDict['population'].append(population.ix[c, y])
            tempDict['income'].append(income.ix[c, y])
    tempDf = pd.DataFrame(tempDict)
    return tempDf
# code CHAR(3),
# year INTEGER,
# GDP FLOAT,
# population FLOAT,
# income FLOAT,
# CPI FLOAT,
economics = getData(countryGDP, countryCPI, countryrevenue, countrypopulation)
economics.to_csv('resources/data clean/economics.csv')
countryGDP.columns

### PerformanceOfCountries

In [52]:
countryOlympics = pd.read_csv('./resources/data clean/1896-2008 sports wise medal records.csv', header=0)
countryOlympicsTemp = countryOlympics[['Edition', 'NOC', 'Medal']]

In [68]:
countryOlympics = countryOlympicsTemp.pivot_table(index=['NOC', 'Edition'], values=['Num'], columns=['Medal'], aggfunc=np.sum)

In [69]:
countryOlympics = countryOlympics.fillna(0)

In [70]:
def addRank(df): #countryOlympicsTemp
#     tempdf = df.groupby(['Edition', 'NOC'])['Num'].sum()
    tempdf = df.pivot_table(index=['NOC', 'Edition'], values=['Num'], columns=['Medal'], aggfunc=np.sum)

               Num
Medal       Bronze  Gold Silver
NOC Edition
AFG 2008       1.0   0.0    0.0
AHO 1988       0.0   0.0    1.0
ALG 1984       2.0   0.0    0.0
    1992       1.0   1.0    0.0
    1996       1.0   2.0    0.0
    2000       3.0   1.0    1.0
    2008       1.0   0.0    1.0
ANZ 1908       2.0  15.0    2.0
    1912       3.0   5.0    2.0
ARG 1924       2.0   6.0    3.0
    1928       5.0   3.0   24.0
    1932       0.0   3.0    1.0
    1936       4.0   5.0    2.0
    1948       1.0   3.0    8.0
    1952       2.0   2.0    2.0
    1956       1.0   0.0    1.0
    1960       1.0   0.0    3.0
    1964       0.0   0.0    1.0
    1968       2.0   0.0    0.0
    1972       0.0   0.0    1.0
    1988      12.0   0.0    1.0
    1992       2.0   0.0    0.0
    1996       1.0   0.0   19.0
    2000       3.0   0.0   17.0
    2004      21.0  26.0    0.0
    2008      31.0  20.0    0.0
ARM 1996       0.0   1.0    1.0
    2000       1.0   0.0    0.0
    2008       6.0   0.0    0.0
AUS 1896       0.0   2.0    0.0
...            ...   ...    ...
VEN 1980       0.0   0.0    1.0
    1984       3.0   0.0    0.0
    2004       2.0   0.0    0.0
    2008       1.0   0.0    0.0
VIE 2000       0.0   0.0    1.0
    2008       0.0   0.0    1.0
YUG 1924       0.0   2.0    0.0
    1928      10.0   1.0    1.0
    1936       0.0   0.0    1.0
    1948       0.0   0.0   16.0
    1952       0.0   4.0   20.0
    1956       0.0   0.0   23.0
    1960       0.0  16.0    1.0
    1964       2.0   2.0   11.0
    1968       2.0  13.0   14.0
    1972       2.0  15.0    1.0
    1976       3.0   2.0   14.0
    1980      17.0  13.0   27.0
    1984      35.0  47.0    5.0
    1988      21.0  15.0   27.0
    1996      13.0   1.0   12.0
    2000      13.0  12.0    1.0
ZAM 1984       1.0   0.0    0.0
    1996       0.0   0.0    1.0
ZIM 1980       0.0  16.0    0.0
    2004       1.0   1.0    1.0
    2008       0.0   1.0    3.0
ZZX 1896       2.0   2.0    2.0
    1900       8.0  18.0    8.0
    1904       0.0   3.0    5.0

[1072 rows x 3 columns]

In [92]:
df

               Num
Medal       Bronze  Gold Silver
NOC Edition
AFG 2008       1.0   0.0    0.0
AHO 1988       0.0   0.0    1.0
ALG 1984       2.0   0.0    0.0
    1992       1.0   1.0    0.0
    1996       1.0   2.0    0.0
    2000       3.0   1.0    1.0
    2008       1.0   0.0    1.0
ANZ 1908       2.0  15.0    2.0
    1912       3.0   5.0    2.0
ARG 1924       2.0   6.0    3.0
    1928       5.0   3.0   24.0
    1932       0.0   3.0    1.0
    1936       4.0   5.0    2.0
    1948       1.0   3.0    8.0
    1952       2.0   2.0    2.0
    1956       1.0   0.0    1.0
    1960       1.0   0.0    3.0
    1964       0.0   0.0    1.0
    1968       2.0   0.0    0.0
    1972       0.0   0.0    1.0
    1988      12.0   0.0    1.0
    1992       2.0   0.0    0.0
    1996       1.0   0.0   19.0
    2000       3.0   0.0   17.0
    2004      21.0  26.0    0.0
    2008      31.0  20.0    0.0
ARM 1996       0.0   1.0    1.0
    2000       1.0   0.0    0.0
    2008       6.0   0.0    0.0
AUS 1896       0.0   2.0    0.0
...            ...   ...    ...
VEN 1980       0.0   0.0    1.0
    1984       3.0   0.0    0.0
    2004       2.0   0.0    0.0
    2008       1.0   0.0    0.0
VIE 2000       0.0   0.0    1.0
    2008       0.0   0.0    1.0
YUG 1924       0.0   2.0    0.0
    1928      10.0   1.0    1.0
    1936       0.0   0.0    1.0
    1948       0.0   0.0   16.0
    1952       0.0   4.0   20.0
    1956       0.0   0.0   23.0
    1960       0.0  16.0    1.0
    1964       2.0   2.0   11.0
    1968       2.0  13.0   14.0
    1972       2.0  15.0    1.0
    1976       3.0   2.0   14.0
    1980      17.0  13.0   27.0
    1984      35.0  47.0    5.0
    1988      21.0  15.0   27.0
    1996      13.0   1.0   12.0
    2000      13.0  12.0    1.0
ZAM 1984       1.0   0.0    0.0
    1996       0.0   0.0    1.0
ZIM 1980       0.0  16.0    0.0
    2004       1.0   1.0    1.0
    2008       0.0   1.0    3.0
ZZX 1896       2.0   2.0    2.0
    1900       8.0  18.0    8.0
    1904       0.0   3.0    5.0

[1072 rows x 3 columns]

In [88]:
d.index[0]

('AFG', 2008)

In [89]:
df.ix[('AFG', 2008), :]

     Medal
Num  Bronze    1.0
     Gold      0.0
     Silver    0.0
Name: (AFG, 2008), dtype: float64